spring.application.name=journal
server.port=8081
spring.mongodb.uri=mongodb+srv://brijalk_db_user:root@cluster0.kpfbbrg.mongodb.net/journaldb?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.auto-index-creation=true